wandb: Currently logged in as: kataoka0511 (junkataoka). Use `wandb login --relogin` to force relogin
wandb: Currently logged in as: kataoka0511 (junkataoka). Use `wandb login --relogin` to force relogin
wandb: wandb version 0.16.4 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.15.3
wandb: Run data is saved locally in /data/home/jkataok1/DA_DFD/wandb/run-20240311_002309-5icwntx6
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run log/gearbox0_spectrogramtogearbox1_spectrogram_lr1e-05_e400_b128
wandb: ‚≠êÔ∏è View project at https://wandb.ai/junkataoka/DA_DFD
wandb: üöÄ View run at https://wandb.ai/junkataoka/DA_DFD/runs/5icwntx6
wandb: wandb version 0.16.4 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.15.3
wandb: Run data is saved locally in /data/home/jkataok1/DA_DFD/wandb/run-20240311_002309-28ohwqnr
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run log/gearbox1_spectrogramtogearbox0_spectrogram_lr1e-05_e400_b128
wandb: ‚≠êÔ∏è View project at https://wandb.ai/junkataoka/DA_DFD
wandb: üöÄ View run at https://wandb.ai/junkataoka/DA_DFD/runs/28ohwqnr
wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.
wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.
wandb: üöÄ View run log/gearbox0_spectrogramtogearbox1_spectrogram_lr1e-05_e400_b128 at: https://wandb.ai/junkataoka/DA_DFD/runs/5icwntx6
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20240311_002309-5icwntx6/logs
wandb: üöÄ View run log/gearbox1_spectrogramtogearbox0_spectrogram_lr1e-05_e400_b128 at: https://wandb.ai/junkataoka/DA_DFD/runs/28ohwqnr
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20240311_002309-28ohwqnr/logs
Traceback (most recent call last):
  File "src/main.py", line 203, in <module>
    main(args)
  File "src/main.py", line 100, in main
    model.load_state_dict(torch.load(os.path.join(args.source_model_path, "_".join([args.src_data, args.src_domain, args.tar_data, args.tar_domain, args.model + ".pth"]))))
  File "/data/home/jkataok1/mlenv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1483, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for ASTModel:
	Missing key(s) in state_dict: "mlp_head.0.weight", "mlp_head.0.bias". 
	Unexpected key(s) in state_dict: "mlp_dis.weight", "mlp_dis.bias", "mlp_head.weight", "mlp_head.bias". 
Traceback (most recent call last):
  File "src/main.py", line 203, in <module>
    main(args)
  File "src/main.py", line 100, in main
    model.load_state_dict(torch.load(os.path.join(args.source_model_path, "_".join([args.src_data, args.src_domain, args.tar_data, args.tar_domain, args.model + ".pth"]))))
  File "/data/home/jkataok1/mlenv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1483, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for ASTModel:
	Missing key(s) in state_dict: "mlp_head.0.weight", "mlp_head.0.bias". 
	Unexpected key(s) in state_dict: "mlp_dis.weight", "mlp_dis.bias", "mlp_head.weight", "mlp_head.bias". 
srun: error: compute130: task 0: Exited with exit code 1
srun: error: compute130: task 0: Exited with exit code 1
